#!/usr/bin/env python3
"""
Create publication-style quantitative summary TABLE FIGURES for the ten top-five
Aβ40/Aβ42 structural-overlay panels already generated by
make_top5_foldseek_pymol_overlays.py.

This script DOES NOT rerun Foldseek or PyMOL and DOES NOT modify source structures.
It reads the existing final source table:

  /home/benla/abeta_project_final/analysis/foldseek/top5_structural_overlays/
      top5_figure_source_data.tsv

and makes one matching quantitative table for each of the ten overlay figures.

Columns:
  prediction/model, nearest experimental reference, qTM, alnTM,
  query coverage, Foldseek RMSD, Contact Jaccard, predicted-contact recovery.

Outputs:
  /home/benla/abeta_project_final/figures/foldseek/top5_structural_overlays/
      quantitative_tables/

Also writes a 50-placement master TSV to the analysis directory.
"""

from __future__ import annotations

from pathlib import Path
import argparse
import re
import textwrap

import matplotlib.pyplot as plt
import pandas as pd

DEFAULT_PROJECT = Path("/home/benla/abeta_project_final")

METHOD_DISPLAY = {
    "AlphaFold": "AlphaFold 3",
    "Boltz": "Boltz-2",
    "Protenix": "Protenix-v2",
    "OpenFold": "OpenFold3",
}
PEPTIDE_DISPLAY = {"ab40": "Aβ40", "ab42": "Aβ42"}


def input_table(project: Path) -> Path:
    return (
        project
        / "analysis"
        / "foldseek"
        / "top5_structural_overlays"
        / "top5_figure_source_data.tsv"
    )


def output_analysis_dir(project: Path) -> Path:
    return project / "analysis" / "foldseek" / "top5_structural_overlays"


def output_table_dir(project: Path) -> Path:
    return (
        project
        / "figures"
        / "foldseek"
        / "top5_structural_overlays"
        / "quantitative_tables"
    )


def template_display(value: str) -> str:
    return "templates" if str(value) == "with_templates" else "no templates"


def clean_pdb_label(value: str) -> str:
    s = str(value).strip()
    m = re.match(r"(?i)^([0-9][A-Za-z0-9]{3})", s)
    return m.group(1).upper() if m else s


def wrap_label(value: str, width: int = 31) -> str:
    return "\n".join(textwrap.wrap(str(value), width=width))


def figure_specs() -> list[tuple[int, str, str, str, str]]:
    # fig_no, selection_scope, peptide, short stem label, title
    return [
        (1, "AlphaFold", "ab40", "ab40_alphafold", "Quantitative validation of the five strongest AlphaFold 3 Aβ40 matches"),
        (2, "AlphaFold", "ab42", "ab42_alphafold", "Quantitative validation of the five strongest AlphaFold 3 Aβ42 matches"),
        (3, "Boltz", "ab40", "ab40_boltz", "Quantitative validation of the five strongest Boltz-2 Aβ40 matches"),
        (4, "Boltz", "ab42", "ab42_boltz", "Quantitative validation of the five strongest Boltz-2 Aβ42 matches"),
        (5, "Protenix", "ab40", "ab40_protenix", "Quantitative validation of the five strongest Protenix-v2 Aβ40 matches"),
        (6, "Protenix", "ab42", "ab42_protenix", "Quantitative validation of the five strongest Protenix-v2 Aβ42 matches"),
        (7, "OpenFold", "ab40", "ab40_openfold", "Quantitative validation of the five strongest OpenFold3 Aβ40 matches"),
        (8, "OpenFold", "ab42", "ab42_openfold", "Quantitative validation of the five strongest OpenFold3 Aβ42 matches"),
        (9, "ALL", "ab40", "ab40_all_methods", "Quantitative validation of the five strongest Aβ40 matches across all four prediction methods"),
        (10, "ALL", "ab42", "ab42_all_methods", "Quantitative validation of the five strongest Aβ42 matches across all four prediction methods"),
    ]


def build_display_name(row: pd.Series, overall: bool) -> str:
    pep = PEPTIDE_DISPLAY[str(row["peptide"])]
    core = (
        f"{pep} {int(row['oligomer_size'])}-mer, "
        f"{template_display(row['template_status'])}, model {int(row['model_rank'])}"
    )
    if overall:
        return f"{METHOD_DISPLAY[str(row['method'])]}: {core}"
    return core


def validate_source(df: pd.DataFrame) -> None:
    required = {
        "selection_scope", "selection_rank", "method", "peptide",
        "template_status", "oligomer_size", "model_rank", "best_pdb_id",
        "qtmscore", "alntmscore", "qcov", "rmsd", "contact_jaccard",
        "predicted_contact_recovery",
    }
    missing = sorted(required - set(df.columns))
    if missing:
        raise RuntimeError(
            "The existing top-five figure source table is missing required columns: "
            + ", ".join(missing)
        )


def assemble_table(rows: pd.DataFrame, title: str, out_stem: Path, overall: bool) -> None:
    rows = rows.sort_values("selection_rank").copy()
    if len(rows) != 5:
        raise RuntimeError(f"Expected 5 rows for {title!r}; found {len(rows)}")

    table_data = pd.DataFrame({
        "Prediction": [build_display_name(row, overall) for _, row in rows.iterrows()],
        "Nearest\nreference": [clean_pdb_label(x) for x in rows["best_pdb_id"]],
        "qTM": rows["qtmscore"],
        "alnTM": rows["alntmscore"],
        "Query\ncoverage": rows["qcov"],
        "Foldseek\nRMSD (Å)": rows["rmsd"],
        "Contact\nJaccard": rows["contact_jaccard"],
        "Predicted-contact\nrecovery": rows["predicted_contact_recovery"],
    })

    table_data["Prediction"] = table_data["Prediction"].map(lambda x: wrap_label(x, 34 if overall else 30))

    numeric_cols = [
        "qTM", "alnTM", "Query\ncoverage", "Foldseek\nRMSD (Å)",
        "Contact\nJaccard", "Predicted-contact\nrecovery",
    ]
    for col in numeric_cols:
        table_data[col] = table_data[col].map(
            lambda x: f"{float(x):.3f}" if pd.notna(x) else "—"
        )

    fig, ax = plt.subplots(figsize=(15.5, 6.2))
    ax.axis("off")

    table = ax.table(
        cellText=table_data.values,
        colLabels=table_data.columns,
        cellLoc="center",
        colLoc="center",
        loc="center",
        colWidths=[0.285, 0.105, 0.072, 0.072, 0.095, 0.105, 0.095, 0.145],
    )
    table.auto_set_font_size(False)
    table.set_fontsize(9.2)
    table.scale(1, 2.25)

    for (row_idx, col_idx), cell in table.get_celld().items():
        cell.set_edgecolor("0.75")
        cell.set_linewidth(0.6)
        if row_idx == 0:
            cell.set_text_props(weight="bold")
            cell.set_facecolor("0.90")
        elif row_idx % 2 == 0:
            cell.set_facecolor("0.96")

    ax.set_title(title, fontsize=16, fontweight="bold", pad=22)
    ax.text(
        0.5,
        0.035,
        (
            "Higher qTM, alnTM, query coverage, Contact Jaccard and predicted-contact recovery "
            "indicate stronger agreement; lower RMSD indicates closer structural superposition."
        ),
        transform=ax.transAxes,
        ha="center",
        fontsize=9,
    )

    out_stem.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_stem.with_suffix(".png"), dpi=600, bbox_inches="tight", facecolor="white")
    fig.savefig(out_stem.with_suffix(".pdf"), bbox_inches="tight", facecolor="white")
    plt.close(fig)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-root", type=Path, default=DEFAULT_PROJECT)
    args = parser.parse_args()

    project = args.project_root.resolve()
    source = input_table(project)
    if not source.is_file():
        raise FileNotFoundError(
            f"Required source table not found:\n  {source}\n\n"
            "Run make_top5_foldseek_pymol_overlays.py --all first."
        )

    df = pd.read_csv(source, sep="\t")
    validate_source(df)

    out_dir = output_table_dir(project)
    out_dir.mkdir(parents=True, exist_ok=True)

    # Save a clean master quantitative table containing all 50 figure placements.
    master = df.copy()
    master["display_prediction"] = [
        build_display_name(row, overall=(str(row["selection_scope"]) == "ALL"))
        for _, row in master.iterrows()
    ]
    keep = [
        "selection_scope", "selection_rank", "peptide", "method",
        "display_prediction", "best_pdb_id", "qtmscore", "alntmscore",
        "qcov", "tcov", "alnlen", "rmsd", "contact_jaccard",
        "predicted_contact_recovery", "experimental_contact_recovery",
    ]
    master_out = output_analysis_dir(project) / "top5_quantitative_summary_50_placements.tsv"
    master[keep].to_csv(master_out, sep="\t", index=False)

    print("=" * 100)
    print("CREATING TEN MATCHED QUANTITATIVE TABLE FIGURES")
    print("=" * 100)
    print(f"Source: {source}")
    print(f"Master TSV: {master_out}")

    for fig_no, scope, peptide, stem_label, title in figure_specs():
        rows = df[(df["selection_scope"] == scope) & (df["peptide"] == peptide)].copy()
        out_stem = out_dir / f"table_{fig_no:02d}_{stem_label}_top5_quantitative"
        assemble_table(rows, title, out_stem, overall=(scope == "ALL"))
        print(f"Table {fig_no:02d}: {out_stem.with_suffix('.png')}")

    print("\n" + "=" * 100)
    print("QUANTITATIVE TABLE FIGURES COMPLETE")
    print("=" * 100)
    print(f"Tables: {out_dir}")
    print("No Foldseek search, PyMOL rendering, or source-structure modification was performed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
